@startuml
start

:Инициализация списка **numbers**;

repeat
  :Генерация случайного числа **num** в заданном диапазоне **low-high**;
  :Вывод числа **num**;
  :Добавление числа **num** в список **numbers**;
  :Запрос ввода пользователя "Введите 0 для остановки...";

repeat while (Введен 0?) is (Нет)
:Вывод всех значений **numbers**, кроме последнего;
stop

@enduml